FROM node:22-alpine

WORKDIR /api

ARG COMMAND="npm run start:dev api"
ENV EXECUTE_COMMAND=$COMMAND
ENV NODE_ENV='docker'

COPY ../../package.json .

RUN npm install

COPY ../../. .

EXPOSE 5000

CMD ["sh", "-c", "${EXECUTE_COMMAND}"]