FROM node:22-alpine

WORKDIR /api

COPY ../../package.json ../../package-lock.json ./

RUN npm ci

COPY ../../node_modules/@prisma/client ./node_modules/@prisma/client
COPY ../../prisma ./prisma

CMD ["sh", "-c", "npm run db:deploy"]