export default Object.freeze({
  NotFound: 'not-found',
  Login: 'login',
  ResetPassword: 'reset-password',
  Personal: 'personal',
  Home: 'home',
  Category: 'category',
  Product: 'product',
  ProductList: 'product-list',
  ProductCreate: 'product-create',
  ProductUpdate: 'product-update',
  Ingredient: 'ingredient',
  IngredientList: 'ingredient-list',
  User: 'user',
  UserList: 'user-list',
  UserCreate: 'user-create',
  UserUpdate: 'user-update',
  Report: 'report',
  Signup: 'signup',
  AllProduct: 'all-product',
  Cart: 'cart',
});
