name: NestJS Microservice CI

on:
  label:
    types: [backend]
  push:
    branches: [*]

env:
  API_PORT: 5000
  USER_MICROSERVICE_TCP_PORT: 5001
  CATEGORY_MICROSERVICE_TCP_PORT: 5002
  INGREDIENT_MICROSERVICE_TCP_PORT: 5003
  PRODUCT_MICROSERVICE_TCP_PORT: 5004
  SOCKET_MICROSERVICE_TCP_PORT: 5005
  SOCKET_PORT: 8000
  ADMIN_ORIGIN_CORS: "http://localhost:3000"
  SALE_ORIGIN_CORS: "http://localhost:3001"
  SESSION_ID_TOKEN: "session_id_token"
  SESSION_EXPIRES: 3600000
  REDIS_HOST: "localhost"
  REDIS_SERVER_PORT: 6379
  SOCKET_PING_INTERVAL: 60000
  SOCKET_PING_TIMEOUT: 60000
  REFRESH_TTL_SEC: 86400
  ADMIN_RESET_PASSWORD_SECRET_KEY: ${{ secrets.ADMIN_RESET_PASSWORD_SECRET_KEY }}
  ADMIN_REFRESH_TOKEN_SECRET_KEY: ${{ secrets.ADMIN_REFRESH_TOKEN_SECRET_KEY }}
  USER_LOGGED_SECRET_KEY: ${{ secrets.USER_LOGGED_SECRET_KEY }}
  API_KEY: ${{ secrets.API_KEY }}
  SMPT_HOST: "smtp.gmail.com"
  SMPT_PORT: 587
  SMPT_MAIL: "huyenthoaihoainam@gmail.com"
  SMPT_APP_PASS: "aajy yqod wllw cchg"
  THROTTLE_TTL: 1000
  THROTTLE_LIMIT: 1

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api

    services:
      redis:
        image: redis
        ports:
          - 6379:6379

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache-dependency-path: api/package.json
          cache: 'npm'

      - name: Install Dependencies
        run: npm i

      - name: Linting
        run: npm run lint -- --quiet

      - name: Run Unit Tests
        run: npm run test:ut:ci

      - name: Run E2E Tests
        run: npm run test:e2e:ci

      - name: Build Application
        run: npm run build
